# Generated by Django 6.0.5 on 2026-05-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerecord',
            old_name='reminder_date',
            new_name='calculatedDate',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='customer_name',
            new_name='customerName',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='service_date',
            new_name='serviceDate',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='vehicle_number',
            new_name='vehicleNumber',
        ),
    ]
