# Generated by Django 6.0.3 on 2026-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_reminder_date_servicerecord_calculateddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
